#! /usr/bin/python3
#
# fontrpmspec-conv
# Copyright (C) 2022 Red Hat, Inc.
#
# Authors:
#   Akira TAGOH  <tagoh@redhat.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import argparse
import sys
from pyfontrpmspec import converter
from pyfontrpmspec import package

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Fonts RPM spec file converter against guidelines',
                                     formatter_class=argparse.ArgumentDefaultsHelpFormatter)

    parser.add_argument('--sourcedir',
                        default='.',
                        help='Source directory')
    parser.add_argument('-o', '--output',
                        default='-',
                        type=argparse.FileType('w'),
                        help='Output file')
    parser.add_argument('SPEC',
                        help='Spec file to convert')

    args = parser.parse_args()

    templates = converter.old2new(args.SPEC, args)
    if templates is None:
        sys.exit(1)

    args.output.write(templates['spec'])
    args.output.close()
    if args.output.name != '<stdout>':
        pkg = package.Package()
        r = pkg.source_name(args.output.name)
        if r != args.output.name:
            print('Proposed spec filename is: {}'.format(r))

    print('Note: You have to review the result. this doesn\'t guarantee the generated spec file can be built as is.', flush=True, file=sys.stderr)
